# Project information
site_name: Reten Documentation
site_url: https://retenai.github.io/public-documentation/
site_description: Documentación técnica de Reten
site_author: Reten Team

# Repository
repo_name: retenai/public-documentation
repo_url: https://github.com/retenai/public-documentation
edit_uri: edit/main/docs/

# Documentation and theme
site_dir: public
docs_dir: docs
theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

# Navigation
nav:
  - Inicio: index.md
  - Entidades:
    - Resumen: entities/README.md
    - Comercios: entities/commerce/README.md
    - Vendedores: entities/seller/README.md
    - Productos: entities/product/README.md
    - Cupones: entities/coupon/README.md
    - Suscripciones: entities/subscription/README.md
    - Categorías: entities/category/README.md
    - Suscripción de Canal: entities/channel_subscription.md
  - Eventos:
    - Resumen: events/README.md
    - Marketing: events/marketing_events.md
    - Ventas: events/sales_events.md
    - Productos: events/product_events.md
    - Usuario: events/user_events.md
    - Entregas: events/delivery_events.md
  - Integración:
    - API de Eventos: integration/events_api.md

# Additional settings
plugins:
  - search
  - minify:
      minify_html: true 