# Project information
site_name: Reten Documentation
site_url: https://retenai.github.io/public-documentation/
site_description: Documentación técnica de Reten
site_author: Reten Team

# Repository
repo_name: retenai/public-documentation
repo_url: https://github.com/retenai/public-documentation
edit_uri: edit/main/docs/

# Documentation and theme
site_dir: public
docs_dir: docs
theme:
  name: material
  language: es
  logo: assets/images/brand/reten-logo-all-white.svg
  favicon: assets/images/brand/favicon.ico
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - assets/stylesheets/extra.css

# Extensions
markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Navigation
nav:
  - :material-home: Inicio: index.md
  - :material-database: Datos Maestros: master-data/README.md
  - :material-cog: Configuraciones: settings/README.md
  - :material-checkbox-marked-circle: Tareas: tasks/README.md
  - :material-chart-timeline-variant: Eventos: events/README.md
  - Datos Maestros:
    - Resumen: master-data/README.md
    - Clientes: master-data/client/README.md
    - Productos: master-data/product/README.md
    - Categorías: master-data/category/README.md
    - Vendedores: master-data/seller/README.md
    - Cupones: master-data/coupon/README.md
    - Transacciones: master-data/transactions/README.md
  - Configuraciones:
    - Resumen: settings/README.md
    - Asignaciones: settings/assignments/README.md
    - Rutas: settings/routes/README.md
    - Suscripciones: settings/subscription/README.md
  - Tareas:
    - Resumen: tasks/README.md
    - Seguimiento: tasks/tracking/README.md
  - Eventos:
    - Resumen: events/README.md
    - Marketing: events/marketing_events.md
    - Ventas: events/sales_events.md
    - Productos: events/product_events.md
    - Usuario: events/user_events.md
    - Entregas: events/delivery_events.md

# Additional settings
plugins:
  - search
  - minify:
      minify_html: true
  - mermaid2:
      version: 10.9.0
      arguments:
        securityLevel: loose
        theme: default
      javascript: https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
  - macros 