# Project information
site_name: Reten Documentation
site_url: https://retenai.github.io/public-documentation/
site_description: Documentación técnica de Reten
site_author: Reten Team

# Repository
repo_name: retenai/public-documentation
repo_url: https://github.com/retenai/public-documentation
edit_uri: edit/main/docs/

# Documentation and theme
site_dir: public
docs_dir: docs
theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

# Navigation
nav:
  - Inicio: index.md
  - Datos Maestros:
    - Resumen: master-data/README.md
    - Categorías: master-data/category/README.md
    - Clientes: master-data/client/README.md
    - Cupones: master-data/coupon/README.md
    - Productos: master-data/product/README.md
    - Transacciones: master-data/transactions/README.md
    - Vendedores: master-data/seller/README.md
  - Tareas:
    - Resumen: tasks/README.md
    - Seguimiento: tasks/tracking/README.md
  - Eventos:
    - Resumen: events/README.md
    - Marketing: events/marketing_events.md
    - Ventas: events/sales_events.md
    - Productos: events/product_events.md
    - Usuario: events/user_events.md
    - Entregas: events/delivery_events.md
  - Configuraciones:
    - Resumen: settings/README.md
    - Asignaciones: settings/assignments/README.md
    - Rutas: settings/routes/README.md
    - Suscripciones: settings/subscription/README.md

# Additional settings
plugins:
  - search
  - minify:
      minify_html: true 